const mongoose = require('mongoose');

const kdaSchema = mongoose.Schema({
    Aatrox: Object,
    Ahri: Object,
    Akali: Object,
    Akshan: Object,
    Alistar: Object,
    Amumu: Object,
    Anivia: Object,
    Annie: Object,
    Aphelios: Object,
    Ashe: Object,
    AurelionSol: Object,
    Azir: Object,
    Bard: Object,
    Blitzcrank: Object,
    Brand: Object,
    Braum: Object,
    Caitlyn: Object,
    Camille: Object,
    Cassiopeia: Object,
    Chogath: Object,
    Corki: Object,
    Darius: Object,
    Diana: Object,
    DrMundo: Object,
    Draven: Object,
    Ekko: Object,
    Elise: Object,
    Evelynn: Object,
    Ezreal: Object,
    Fiddlesticks: Object,
    Fiora: Object,
    Fizz: Object,
    Galio: Object,
    Gangplank: Object,
    Garen: Object,
    Gnar: Object,
    Gragas: Object,
    Graves: Object,
    Gwen: Object,
    Hecarim: Object,
    Heimerdinger: Object,
    Illaoi: Object,
    Irelia: Object,
    Ivern: Object,
    Janna: Object,
    JarvanIV: Object,
    Jax: Object,
    Jayce: Object,
    Jhin: Object,
    Jinx: Object,
    Kaisa: Object,
    Kalista: Object,
    Karma: Object,
    Karthus: Object,
    Kassadin: Object,
    Katarina: Object,
    Kayle: Object,
    Kayn: Object,
    Kennen: Object,
    Khazix: Object,
    Kindred: Object,
    Kled: Object,
    Kogmaw: Object,
    Leblanc: Object,
    LeeSin: Object,
    Leona: Object,
    Lillia: Object,
    Lissandra: Object,
    Lucian: Object,
    Lulu: Object,
    Lux: Object,
    Malphite: Object,
    Malzahar: Object,
    Maokai: Object,
    MasterYi: Object,
    MissFortune: Object,
    Mordekaiser: Object,
    Morgana: Object,
    Nami: Object,
    Nasus: Object,
    Nautilus: Object,
    Neeko: Object,
    Nidalee: Object,
    Nocturne: Object,
    Nunu: Object,
    Olaf: Object,
    Orianna: Object,
    Ornn: Object,
    Pantheon: Object,
    Poppy: Object,
    Pyke: Object,
    Qiyana: Object,
    Quinn: Object,
    Rakan: Object,
    Rammus: Object,
    RekSai: Object,
    Rell: Object,
    Renekton: Object,
    Rengar: Object,
    Riven: Object,
    Rumble: Object,
    Ryze: Object,
    Samira: Object,
    Sejuani: Object,
    Senna: Object,
    Seraphine: Object,
    Sett: Object,
    Shaco: Object,
    Shen: Object,
    Shyvana: Object,
    Singed: Object,
    Sion: Object,
    Sivir: Object,
    Skarner: Object,
    Sona: Object,
    Soraka: Object,
    Swain: Object,
    Sylas: Object,
    Syndra: Object,
    TahmKench: Object,
    Taliyah: Object,
    Talon: Object,
    Taric: Object,
    Teemo: Object,
    Thresh: Object,
    Tristana: Object,
    Trundle: Object,
    Tryndamere: Object,
    TwistedFate: Object,
    Twitch: Object,
    Udyr: Object,
    Urgot: Object,
    Varus: Object,
    Vayne: Object,
    Veigar: Object,
    Velkoz: Object,
    Vex: Object,
    Vi: Object,
    Viego: Object,
    Viktor: Object,
    Vladimir: Object,
    Volibear: Object,
    Warwick: Object,
    Wukong: Object,
    Xayah: Object,
    Xerath: Object,
    XinZhao: Object,
    Yasuo: Object,
    Yone: Object,
    Yorick: Object,
    Yuumi: Object,
    Zac: Object,
    Zed: Object,
    Ziggs: Object,
    Zilean: Object,
    Zoe: Object,
    Zyra: Object,
});

const kdaTop = mongoose.model('matchTop', kdaSchema, 'matchTop');
const kdaJungle = mongoose.model('matchJungle', kdaSchema, 'matchJungle');
const kdaMiddle = mongoose.model('matchMid', kdaSchema, 'matchMid');
const kdaBottom = mongoose.model('matchBot', kdaSchema, 'matchBot');
const kdaUtility = mongoose.model('matchSup', kdaSchema, 'matchSup');

module.exports = {
    kdaTop,
    kdaJungle,
    kdaMiddle,
    kdaBottom,
    kdaUtility,
};
